#### Basic Practice

In [1]:
import pandas as pd

In [2]:
print("Steve")

Steve

In [6]:
df = pd.DataFrame([[1,2,3],[2,3,4],[4,5,6]],columns=["A","B","C"])

In [7]:
df

   A  B  C
0  1  2  3
1  2  3  4
2  4  5  6

In [13]:
data = {
    "Name" : ["Ranbir", "Steve"],
    "Age" : [43, 33],
    "City" : ["Mumbai", "Hawkins"]
}
df = pd.DataFrame(data, index= [1,2])

In [14]:
df

     Name  Age     City
1  Ranbir   43   Mumbai
2   Steve   33  Hawkins

In [17]:
df["Name"]

1    Ranbir
2     Steve
Name: Name, dtype: str

In [19]:
df[["Name","Age"]]

     Name  Age
1  Ranbir   43
2   Steve   33

In [21]:
df[df["Age"]>40]

     Name  Age    City
1  Ranbir   43  Mumbai

In [22]:
df.groupby("City")["Name"].count()

City
Hawkins    1
Mumbai     1
Name: Name, dtype: int64

In [23]:
df=pd.read_csv("results.csv")

In [24]:
df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [25]:
df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [26]:
df.isnull().sum()

year            2601
type            2601
discipline         1
event              0
as                 0
athlete_id         0
noc                1
team          186694
place          25215
tied               0
medal         264269
dtype: int64

In [29]:
df.iloc[308403]

year                          2022.0
type                          Winter
discipline                      Luge
event         Singles, Men (Olympic)
as                     Marián Skupek
athlete_id                    148983
noc                              SVK
team                             NaN
place                           26.0
tied                           False
medal                            NaN
Name: 308403, dtype: object

In [30]:
df.iloc[0:4]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN

# Main Practice Starts Here
# Basic

## DataFrame Creation

In [31]:
data ={
    "Product" : ["Rice", "Oil", "Suger", "Salt"],
    "Price" : [60, 180, 90, 30],
    "Quantity" : [100, 50, 80, 200],
    "Category" : ["Grocery", "Grocery", "Grocery", "Grocery"]
}
df= pd.DataFrame(data)
df

  Product  Price  Quantity Category
0    Rice     60       100  Grocery
1     Oil    180        50  Grocery
2   Suger     90        80  Grocery
3    Salt     30       200  Grocery

## Observe DataFrame

In [32]:
df.head()

  Product  Price  Quantity Category
0    Rice     60       100  Grocery
1     Oil    180        50  Grocery
2   Suger     90        80  Grocery
3    Salt     30       200  Grocery

In [34]:
df.tail(2)

  Product  Price  Quantity Category
2   Suger     90        80  Grocery
3    Salt     30       200  Grocery

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   4 non-null      str
 1   Price     4 non-null      int64
 2   Quantity  4 non-null      int64
 3   Category  4 non-null      str
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [36]:
df.describe()

            Price  Quantity
count    4.000000       4.0
mean    90.000000     107.5
std     64.807407      65.0
min     30.000000      50.0
25%     52.500000      72.5
50%     75.000000      90.0
75%    112.500000     125.0
max    180.000000     200.0

In [38]:
df.shape

(4, 4)

In [39]:
df.columns

Index(['Product', 'Price', 'Quantity', 'Category'], dtype='str')

In [40]:
df.dtypes

Product       str
Price       int64
Quantity    int64
Category      str
dtype: object

## Selection and Indexing

In [41]:
df= pd.DataFrame({
    'Name':['Ranbir','Kabir','Steve','Nancy','Jonas'],
    'Age':[43, 30, 33, 32, 23],
    'City':['Mumbai','Dehli','Hawkins','Hawkins','Winden'],
    'Salary': [50000, 45000, 30000, 40000, 30000]
})

In [42]:
df['Name']

0    Ranbir
1     Kabir
2     Steve
3     Nancy
4     Jonas
Name: Name, dtype: str

In [43]:
df[['Name','Age']]

     Name  Age
0  Ranbir   43
1   Kabir   30
2   Steve   33
3   Nancy   32
4   Jonas   23

In [44]:
df.loc[2]

Name        Steve
Age            33
City      Hawkins
Salary      30000
Name: 2, dtype: object

In [45]:
df.loc[0:2]

     Name  Age     City  Salary
0  Ranbir   43   Mumbai   50000
1   Kabir   30    Dehli   45000
2   Steve   33  Hawkins   30000

In [47]:
df.loc[0:2, 'Name':'City']

     Name  Age     City
0  Ranbir   43   Mumbai
1   Kabir   30    Dehli
2   Steve   33  Hawkins

In [49]:
df.iloc[1]

Name      Kabir
Age          30
City      Dehli
Salary    45000
Name: 1, dtype: object

In [50]:
df.iloc[0:2 , 0:3]

     Name  Age    City
0  Ranbir   43  Mumbai
1   Kabir   30   Dehli

In [51]:
df[df['Age']>25]

     Name  Age     City  Salary
0  Ranbir   43   Mumbai   50000
1   Kabir   30    Dehli   45000
2   Steve   33  Hawkins   30000
3   Nancy   32  Hawkins   40000

In [52]:
df[df['City']=='Hawkins']

    Name  Age     City  Salary
2  Steve   33  Hawkins   30000
3  Nancy   32  Hawkins   40000

In [54]:
df[(df['City']=='Hawkins')& (df['Age']>32)]

    Name  Age     City  Salary
2  Steve   33  Hawkins   30000

In [57]:
df[df['City'].isin(['Hawkins','Mumbai'])]

     Name  Age     City  Salary
0  Ranbir   43   Mumbai   50000
2   Steve   33  Hawkins   30000
3   Nancy   32  Hawkins   40000

# Intermediate

## Data Cleaning

In [59]:
import numpy as np

In [60]:
df = pd.DataFrame({
    'Name': ['Rahim', 'Karim', None, 'Nusrat'],
    'Age': [25, np.nan, 22, 28],
    'Salary': [35000, 45000, 30000, None]
})

In [61]:
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2   True  False   False
3  False  False    True

In [62]:
df.isnull().sum()

Name      1
Age       1
Salary    1
dtype: int64

In [63]:
df.dropna()

    Name   Age   Salary
0  Rahim  25.0  35000.0

In [65]:
df.dropna(subset=['Name'])

     Name   Age   Salary
0   Rahim  25.0  35000.0
1   Karim   NaN  45000.0
3  Nusrat  28.0      NaN

In [67]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_14320\1698716155.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(), inplace=True)

0    25.0
1    25.0
2    22.0
3    28.0
Name: Age, dtype: float64

In [68]:
df['Name'].fillna('Unknown', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_14320\3346711072.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Name'].fillna('Unknown', inplace=True)

0      Rahim
1      Karim
2    Unknown
3     Nusrat
Name: Name, dtype: str

In [70]:
df.ffill()

     Name   Age   Salary
0   Rahim  25.0  35000.0
1   Karim  25.0  45000.0
2   Karim  22.0  30000.0
3  Nusrat  28.0  30000.0

In [71]:
df.duplicate()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

# Data Transformation

In [72]:
df = pd.DataFrame({
    'Name': ['Rahim', 'Karim', 'Salma'],
    'Salary': [40000, 45000, 30000],
    'Bonus_Percent': [10, 15, 5]
})

In [73]:
df['Bonus'] = df['Salary']*df['Bonus_Percent']/100

In [74]:
df

    Name  Salary  Bonus_Percent   Bonus
0  Rahim   40000             10  4000.0
1  Karim   45000             15  6750.0
2  Salma   30000              5  1500.0

In [75]:
df['Total'] = df['Salary']+df['Bonus']
df

    Name  Salary  Bonus_Percent   Bonus    Total
0  Rahim   40000             10  4000.0  44000.0
1  Karim   45000             15  6750.0  51750.0
2  Salma   30000              5  1500.0  31500.0

In [77]:
def tax_bracket(salary):
    if salary > 40000:
        return 'High'
    else:
        return 'Low'

df['Tax_Bracket'] = df['Salary'].apply(tax_bracket)   

df

    Name  Salary  Bonus_Percent   Bonus    Total Tax_Bracket
0  Rahim   40000             10  4000.0  44000.0         Low
1  Karim   45000             15  6750.0  51750.0        High
2  Salma   30000              5  1500.0  31500.0         Low

In [80]:
df.sort_values('Salary', ascending=False)

    Name  Salary  Bonus_Percent   Bonus    Total Tax_Bracket
1  Karim   45000             15  6750.0  51750.0        High
0  Rahim   40000             10  4000.0  44000.0         Low
2  Salma   30000              5  1500.0  31500.0         Low

In [82]:
df.sort_values(['Bonus','Salary'], ascending=[True,False])

    Name  Salary  Bonus_Percent   Bonus    Total Tax_Bracket
2  Salma   30000              5  1500.0  31500.0         Low
0  Rahim   40000             10  4000.0  44000.0         Low
1  Karim   45000             15  6750.0  51750.0        High

In [83]:
df.rename(columns={'Salary':'Monthly_Salary'})

    Name  Monthly_Salary  Bonus_Percent   Bonus    Total Tax_Bracket
0  Rahim           40000             10  4000.0  44000.0         Low
1  Karim           45000             15  6750.0  51750.0        High
2  Salma           30000              5  1500.0  31500.0         Low

## GroupBy & Aggregation

In [84]:
sales = pd.DataFrame({
    'Region': ['Dhaka', 'Ctg', 'Dhaka', 'Sylhet', 'Ctg', 'Dhaka'],
    'Product': ['A', 'B', 'A', 'A', 'B', 'B'],
    'Sales': [1000, 1500, 1200, 800, 2000, 900],
    'Month': ['Jan', 'Jan', 'Feb', 'Feb', 'Jan', 'Feb']
})

In [85]:
sales

   Region Product  Sales Month
0   Dhaka       A   1000   Jan
1     Ctg       B   1500   Jan
2   Dhaka       A   1200   Feb
3  Sylhet       A    800   Feb
4     Ctg       B   2000   Jan
5   Dhaka       B    900   Feb

In [87]:
sales.groupby('Region')['Sales'].sum()

Region
Ctg       3500
Dhaka     3100
Sylhet     800
Name: Sales, dtype: int64

In [88]:
sales.groupby('Region')['Sales'].agg(['sum','mean','count','max'])

         sum         mean  count   max
Region
Ctg     3500  1750.000000      2  2000
Dhaka   3100  1033.333333      3  1200
Sylhet   800   800.000000      1   800

In [89]:
sales.groupby(['Region','Product'])['Sales'].sum()

Region  Product
Ctg     B          3500
Dhaka   A          2200
        B           900
Sylhet  A           800
Name: Sales, dtype: int64

In [91]:
sales.groupby('Region').agg(
    Total_Sales=('Sales','sum'),
    Avg_Sales=('Sales','mean')
)

        Total_Sales    Avg_Sales
Region
Ctg            3500  1750.000000
Dhaka          3100  1033.333333
Sylhet          800   800.000000

In [93]:
pd.pivot_table(sales, values='Sales', index='Region', columns= 'Month', aggfunc='sum', fill_value=0)

Month    Feb   Jan
Region
Ctg        0  3500
Dhaka   2100  1000
Sylhet   800     0

## Merging

In [94]:
employees = pd.DataFrame({
    'EmpID': [1, 2, 3, 4],
    'Name': ['Rahim', 'Karim', 'Salma', 'Nusrat'],
    'DeptID': [10, 20, 10, 30]
})
employees

   EmpID    Name  DeptID
0      1   Rahim      10
1      2   Karim      20
2      3   Salma      10
3      4  Nusrat      30

In [96]:
departments = pd.DataFrame({
    'DeptID': [10, 20, 30],
    'DeptName': ['Sales', 'IT', 'HR']
})
departments

   DeptID DeptName
0      10    Sales
1      20       IT
2      30       HR

In [97]:
merged = pd.merge(employees, departments, on='DeptID', how='left')

In [98]:
merged

   EmpID    Name  DeptID DeptName
0      1   Rahim      10    Sales
1      2   Karim      20       IT
2      3   Salma      10    Sales
3      4  Nusrat      30       HR

## Concatination

In [100]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'A':[3,4]})

In [101]:
df1

   A
0  1
1  2

In [102]:
df2

   A
0  3
1  4

In [103]:
combined = pd.concat([df1,df2], ignore_index= True)

In [104]:
combined

   A
0  1
1  2
2  3
3  4