# MultiIndex

In [2]:
import pandas as pd

In [3]:
sales = pd.DataFrame({
    'Region': ['Dhaka','Dhaka','Ctg','Ctg'],
    'Year': [2023, 2024, 2023, 2024],
    'Sales': [10000, 12000, 8000, 9500]
})

sales

  Region  Year  Sales
0  Dhaka  2023  10000
1  Dhaka  2024  12000
2    Ctg  2023   8000
3    Ctg  2024   9500

In [4]:
multi = sales.set_index(['Region', 'Year'])

In [5]:
multi

             Sales
Region Year
Dhaka  2023  10000
       2024  12000
Ctg    2023   8000
       2024   9500

In [11]:
multi.loc[('Dhaka',2024)]

Sales    12000
Name: (Dhaka, 2024), dtype: int64

## Stack Unstack

In [12]:
pivoted = sales.pivot(index='Region', columns='Year',values='Sales')
stacked = pivoted.stack()

In [13]:
stacked

Region  Year
Ctg     2023     8000
        2024     9500
Dhaka   2023    10000
        2024    12000
dtype: int64

In [15]:
unstacked = pivoted.unstack()
unstacked

Year  Region
2023  Ctg        8000
      Dhaka     10000
2024  Ctg        9500
      Dhaka     12000
dtype: int64

In [16]:
pivoted

Year     2023   2024
Region
Ctg      8000   9500
Dhaka   10000  12000

# Time Series

### Creating Datetime

In [18]:
dates = pd.date_range(start='2024-01-01', periods=10, freq='D')

In [19]:
import numpy as np

In [35]:
ts = pd.DataFrame({
    'Date': dates,
    'Sales': np.random.randint(100,500,10)
})

In [36]:
ts

        Date  Sales
0 2024-01-01    105
1 2024-01-02    152
2 2024-01-03    243
3 2024-01-04    129
4 2024-01-05    433
5 2024-01-06    188
6 2024-01-07    129
7 2024-01-08    117
8 2024-01-09    174
9 2024-01-10    477

In [37]:
ts['Date']=pd.to_datetime(ts['Date'])

In [38]:
ts.set_index('Date',inplace=True)

In [39]:
ts

            Sales
Date
2024-01-01    105
2024-01-02    152
2024-01-03    243
2024-01-04    129
2024-01-05    433
2024-01-06    188
2024-01-07    129
2024-01-08    117
2024-01-09    174
2024-01-10    477

In [40]:
ts['Year']=ts.index.year

In [41]:
ts

            Sales  Year
Date
2024-01-01    105  2024
2024-01-02    152  2024
2024-01-03    243  2024
2024-01-04    129  2024
2024-01-05    433  2024
2024-01-06    188  2024
2024-01-07    129  2024
2024-01-08    117  2024
2024-01-09    174  2024
2024-01-10    477  2024

In [42]:
ts['Month']=ts.index.month
ts['Weekday']=ts.index.day_name()
ts

            Sales  Year  Month    Weekday
Date
2024-01-01    105  2024      1     Monday
2024-01-02    152  2024      1    Tuesday
2024-01-03    243  2024      1  Wednesday
2024-01-04    129  2024      1   Thursday
2024-01-05    433  2024      1     Friday
2024-01-06    188  2024      1   Saturday
2024-01-07    129  2024      1     Sunday
2024-01-08    117  2024      1     Monday
2024-01-09    174  2024      1    Tuesday
2024-01-10    477  2024      1  Wednesday

In [44]:
ts.resample('D').sum()

            Sales  Year  Month    Weekday
Date
2024-01-01    105  2024      1     Monday
2024-01-02    152  2024      1    Tuesday
2024-01-03    243  2024      1  Wednesday
2024-01-04    129  2024      1   Thursday
2024-01-05    433  2024      1     Friday
2024-01-06    188  2024      1   Saturday
2024-01-07    129  2024      1     Sunday
2024-01-08    117  2024      1     Monday
2024-01-09    174  2024      1    Tuesday
2024-01-10    477  2024      1  Wednesday

In [54]:
dates= pd.date_range(start='2026-06-01', periods=10, freq='D')
ts2=pd.DataFrame({
    'Date':dates,
    'Sales': np.random.randint(100,500,10)
})
ts2['Date']=pd.to_datetime(ts2['Date'])
ts2.set_index('Date', inplace=True)
ts2

            Sales
Date
2026-06-01    414
2026-06-02    336
2026-06-03    374
2026-06-04    478
2026-06-05    244
2026-06-06    296
2026-06-07    114
2026-06-08    312
2026-06-09    341
2026-06-10    155

In [55]:
ts2.resample('W').sum()

            Sales
Date
2026-06-07   2256
2026-06-14    808

In [61]:
ts2['7Day_Avg']=ts2['Sales'].rolling(window=7).mean()

In [62]:
ts2

            Sales    7Day_Avg
Date
2026-06-01    414         NaN
2026-06-02    336         NaN
2026-06-03    374         NaN
2026-06-04    478         NaN
2026-06-05    244         NaN
2026-06-06    296         NaN
2026-06-07    114  322.285714
2026-06-08    312  307.714286
2026-06-09    341  308.428571
2026-06-10    155  277.142857

In [63]:
ts2['Previous_day']= ts2['Sales'].shift(1)
ts2

            Sales    7Day_Avg  Previous_day
Date
2026-06-01    414         NaN           NaN
2026-06-02    336         NaN         414.0
2026-06-03    374         NaN         336.0
2026-06-04    478         NaN         374.0
2026-06-05    244         NaN         478.0
2026-06-06    296         NaN         244.0
2026-06-07    114  322.285714         296.0
2026-06-08    312  307.714286         114.0
2026-06-09    341  308.428571         312.0
2026-06-10    155  277.142857         341.0

# Performance Optimization

## Vectorization

In [64]:
df = pd.DataFrame({
    'A' : range(1000000)
})
df

             A
0            0
1            1
2            2
3            3
4            4
...        ...
999995  999995
999996  999996
999997  999997
999998  999998
999999  999999

[1000000 rows x 1 columns]

In [65]:
df['B'] = df['A']*2
df

             A        B
0            0        0
1            1        2
2            2        4
3            3        6
4            4        8
...        ...      ...
999995  999995  1999990
999996  999996  1999992
999997  999997  1999994
999998  999998  1999996
999999  999999  1999998

[1000000 rows x 2 columns]

## Query

In [66]:
df.query('A>20000')

             A        B
20001    20001    40002
20002    20002    40004
20003    20003    40006
20004    20004    40008
20005    20005    40010
...        ...      ...
999995  999995  1999990
999996  999996  1999992
999997  999997  1999994
999998  999998  1999996
999999  999999  1999998

[979999 rows x 2 columns]

## Eval

In [67]:
df.eval('C=A+B', inplace=True)

In [68]:
df

             A        B        C
0            0        0        0
1            1        2        3
2            2        4        6
3            3        6        9
4            4        8       12
...        ...      ...      ...
999995  999995  1999990  2999985
999996  999996  1999992  2999988
999997  999997  1999994  2999991
999998  999998  1999996  2999994
999999  999999  1999998  2999997

[1000000 rows x 3 columns]

## Memory Optimization

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   A       1000000 non-null  int64
 1   B       1000000 non-null  int64
 2   C       1000000 non-null  int64
dtypes: int64(3)
memory usage: 22.9 MB

In [70]:
df['A'] = df['A'].astype('int32')

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   A       1000000 non-null  int32
 1   B       1000000 non-null  int64
 2   C       1000000 non-null  int64
dtypes: int32(1), int64(2)
memory usage: 19.1 MB

In [78]:
df = pd.DataFrame({
    'City': ['Dhaka', 'Ctg', 'Sylhet', 'Khulna', 'Rajshahi', 'Dhaka', 'Ctg']  
})

In [79]:
df

       City
0     Dhaka
1       Ctg
2    Sylhet
3    Khulna
4  Rajshahi
5     Dhaka
6       Ctg

In [80]:
df['City'] = df['City'].astype('category')

In [82]:
df['City']

0       Dhaka
1         Ctg
2      Sylhet
3      Khulna
4    Rajshahi
5       Dhaka
6         Ctg
Name: City, dtype: category
Categories (5, str): ['Ctg', 'Dhaka', 'Khulna', 'Rajshahi', 'Sylhet']

## Reshaping

### melt

In [83]:
wide = pd.DataFrame({
    'Name': ['Rahim', 'Karim'],
    'Math': [80, 90],
    'Science': [85, 88]
})

In [84]:
wide

    Name  Math  Science
0  Rahim    80       85
1  Karim    90       88

In [85]:
long = wide.melt(id_vars='Name', var_name='Subject', value_name='Marks')
long

    Name  Subject  Marks
0  Rahim     Math     80
1  Karim     Math     90
2  Rahim  Science     85
3  Karim  Science     88

### pivot

In [87]:
back = long.pivot(index='Name', columns='Subject', values='Marks')
back

Subject  Math  Science
Name
Karim      90       88
Rahim      80       85

## Method Chaining & Pipe

In [88]:
sales = pd.DataFrame({
    'Region': ['Dhaka','Ctg','Dhaka'],
    'Sales': [5000, None, 3000]
})
sales

  Region   Sales
0  Dhaka  5000.0
1    Ctg     NaN
2  Dhaka  3000.0

In [91]:
result = (
    sales
    .pipe(clean_data)
    .pipe(add_column)
    .sort_values('Sales', ascending=False)
    .reset_index(drop=True)
)

In [93]:
result

  Region   Sales     New
0  Dhaka  5000.0  5500.0
1  Dhaka  3000.0  3300.0

## String

In [94]:
users = pd.DataFrame({
    'Email': ['Rahim@Gmail.com', 'karim@yahoo.COM', ' salma@gmail.com ']
})
users

               Email
0    Rahim@Gmail.com
1    karim@yahoo.COM
2   salma@gmail.com

In [95]:
users['Email'] = users['Email'].str.lower().str.strip()

In [96]:
users

             Email
0  rahim@gmail.com
1  karim@yahoo.com
2  salma@gmail.com

In [97]:
users['Domain'] = users['Email'].str.split('@').str[1]
users

             Email     Domain
0  rahim@gmail.com  gmail.com
1  karim@yahoo.com  yahoo.com
2  salma@gmail.com  gmail.com

In [98]:
users['Is_Gmail'] = users['Email'].str.contains('gmail')
users

             Email     Domain  Is_Gmail
0  rahim@gmail.com  gmail.com      True
1  karim@yahoo.com  yahoo.com     False
2  salma@gmail.com  gmail.com      True